In [1]:
# 모든 operation func을 실행할 때, 기준이 되는 dimension 축
import numpy as np

In [5]:
test_array = np.arange(1,21).reshape(-1,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [6]:
test_array.sum(axis=1)

array([10, 26, 42, 58, 74])

In [7]:
test_array.sum(axis=0) # axis=0이 되는 축은 새로 생기는 축

array([45, 50, 55, 60])

In [8]:
# 3차원
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]])

In [9]:
third_order_tensor.sum(axis=0) 

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [10]:
third_order_tensor.sum(axis=1)

array([[45, 50, 55, 60],
       [45, 50, 55, 60],
       [45, 50, 55, 60]])

In [11]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42, 58, 74],
       [10, 26, 42, 58, 74],
       [10, 26, 42, 58, 74]])