In [6]:
# 가상환경 생성하기
# conda create --name (가상환경 이름) python=3.9 (설치하고 싶은 모듈들numpy,matplotlib,tqdm 등)
# conda env list 가상환경 목록 확인
# conda remove --name (가상환경 이름) --all 가상환경 삭제
# conda activate (가상환경 이름) / conda deactivate 
# 주피터 노트북에 가상환경 등록하기
# conda install ipykernel
# python -m ipykernel install --user --name (가상환경 이름) --display-name "(가상환경 이름)"
# jupyter notebook
# 주피터: new -> (파이썬 대신 가상환경 이름 선택)

import numpy as np # dynamic typing을 지원하지 않음

In [2]:
test_array = np.array(["1","4",5,8],float)
test_array # 그냥 list에서는 다양한 자료형이 리스트에 섞여 들어갈 수 있으나
# 하지만 numpy는 리스트에 하나의 자료형만 들어갈 수 있음 그래서 결과가 float으로 됌

array([1., 4., 5., 8.])

In [3]:
type(test_array[3]) # 64비트 하나의 데이터가 차지하는 양이 64bit

numpy.float64

In [11]:
test_array = np.array([1,4,5,"8"],np.float32) # string type의 데이터
test_array

array([1., 4., 5., 8.], dtype=float32)

In [7]:
 type(test_array[3]) # float type으로 자동 형변환 실시

numpy.float64

In [8]:
test_array.dtype # 배열 전체의 데이터 타입을 반환함

dtype('float64')

In [9]:
test_array

array([1., 4., 5., 8.])

In [10]:
test_array.shape # 배열의 shape을 반환 -> 행이 4개 열이 0개 matrix

(4,)