In [1]:
import numpy as np

In [2]:
test_example = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],int)
test_example[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
test_example[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [5]:
test_example[1,:2]

array([5, 6])

In [6]:
test_example[1:3,2]

array([ 7, 11])