In [1]:
import numpy as np

In [2]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [3]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [5]:
test = np.array(test_matrix).reshape(8,)
test

array([1, 2, 3, 4, 1, 2, 5, 8])

In [6]:
# np.array(test_matrix).reshape(-1,2).shape # -1:size를 기반으로 row 개수 선정
test.reshape(-1,1) # col만 정해주면 row는 맞춰서 개수 선정

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [5],
       [8]])

In [8]:
np.array(test_matrix).reshape(2,4)

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [9]:
test_matrix2 = [[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]
np.array(test_matrix2).flatten() # flatten : 3차원 matrix를 1차원 matrix로 변환시키는 함수

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])